### ISSUE TITLE
Error with SchemaType Array

### ISSUE THREAD

**Issue by cbweaver** [ethanresnick/json-api#109]
node version: 5.3.0
json-api version: 2.15.6
I receive the following error when trying to run my app:

```
/home/vagrant/app/node_modules/json-api/build/src/db-adapters/Mongoose/MongooseAdapter.js:649
        var baseType = holdsArray ? typeOptions[0].type.name : typeOptions.name;
                                                       ^

TypeError: Cannot read property 'name' of undefined
    at getFieldType (/home/vagrant/app/node_modules/json-api/build/src/db-adapters/Mongoose/MongooseAdapter.js:649:56)
    at /home/vagrant/app/node_modules/json-api/build/src/db-adapters/Mongoose/MongooseAdapter.js:660:25
    at Schema.eachPath (/home/vagrant/app/node_modules/mongoose/lib/schema.js:609:5)
    at Function.getStandardizedSchema (/home/vagrant/app/node_modules/json-api/build/src/db-adapters/Mongoose/MongooseAdapter.js:655:20)
    at DocumentationController.getTypeInfo (/home/vagrant/app/node_modules/json-api/build/src/controllers/Documentation.js:151:40)
    at /home/vagrant/app/node_modules/json-api/build/src/controllers/Documentation.js:84:43
    at Array.forEach (native)
    at new DocumentationController (/home/vagrant/app/node_modules/json-api/build/src/controllers/Documentation.js:83:31)
    at Object.<anonymous> (/home/vagrant/app/src/index.js:27:12)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

This is my model:
```
'use strict';
var mongoose   = require('mongoose');

var schema = mongoose.Schema({
  name: {
    common: [String],
    scientific: String
  },
  climate: {
    temperature: {
      min: Number,
      max: Number
    }
  }
});

module.exports = mongoose.model('Plant', schema);
```

I don't have a full grasp of why the ".type" is included, but removing it fixes the error completely. Documentation is generated properly ("Array[String]") if I remove ".type" from line 649 of MongooseAdapter.js:
```
var baseType = holdsArray ? typeOptions[0].name : typeOptions.name;
```

**Comment by ethanresnick** [comment]
Thanks so much for reporting this! I'll try to look into it, and add a fix with some tests, in the next few days. I'd also happily merge a PR if it came with tests to make sure that removing `.type` didn't break other cases. The mongoose schema objects are pretty funky and largely undocumented, so I suspect the `.type` was added because there's some other case that needs it.

**Comment by Jwsonic** [comment]
I too have run into the same issues as @cbweaver. Even down to removing `.type` causing the code to work properly. 

I did a fresh git clone of the json-api repo and tried to run the tests after an npm install, but half of them failed without any changes to the repo. Is there anything else I need to do before running npm test?

**Comment by BrianSipple** [comment]
After digging into the Mongoose source code a bit, I came across [how the `Document.prototype.set` function is handling the same situation](schemaName
https://github.com/Automattic/mongoose/blob/48f9bbcf2530b220f1cea95f82f49921d02f2e75/lib/document.js#L659)

The relevant parts in that link:
```
    if (schema.options &&
        Array.isArray(schema.options.type) &&
        schema.options.type.length &&
        schema.options.type[0].ref &&
        Array.isArray(val) &&
        val.length > 0 &&
        val[0] instanceof Document &&
        val[0].constructor.modelName &&
        schema.options.type[0].ref === val[0].constructor.modelName) {

   .........
}
```

It appears as though what we're looking for on `typeOptions[0].type.name` is actually defined on `typeOptions[0].ref` (which is further demonstrated by the strict equality check of schema.options.type[0].ref === val[0].constructor.modelName)`).

I submitted a PR and updated the Schema used in the `getStandardizedSchema` tests to have a property that referenced an Array schemaType. The tests failed with the same error reported here when using the old implementation; they pass with the new implementation. My project that was also experiencing this same error is now running properly with this change linked locally.

**Comment by figliohulio** [comment]
@BrianSipple, I'm sorry, but these changes have not fixed the bug, but only make it implicitly.

Please check it: `build/src/db-adapters/Mongoose/MongooseAdapter.js`
```diff
        var holdsArray = Array.isArray(typeOptions);
 
         var baseType = holdsArray ? typeOptions[0].ref : typeOptions.name;
+
+        if (holdsArray) {
+          console.log(baseType); // undefined
+        }
+
         var refModelName = util.getReferencedModelName(model, path);
```
This bug still leads to the same error when trying to use `DocumentationController`.

`schemaType.options.type[0].ref` is only present in the case of relationship with another model, and is absent in the other cases (**single** relationship, array of symple types or subdocs). In the case when the field is a sub-document, relationship with another model or an array of sub-documents or relationships, we do not need to touch any `schemaType.options.type[0].ref`, or `schemaType.options.type[0].name`:
```javascript
var typeOptions = holdsArray ?
  schemaType.options.type[0] :
  schemaType.options.type;

var isEmbeddedDocument = (
  schemaType.constructor.name === "SchemaType" ||
  schemaType.constructor.name === "DocumentArray"
);

var baseType = isEmbeddedDocument ?
  'EmbeddedDocument' :
  typeOptions.name;
```
However, if the field will be an array of relationships, the `typeOptions.name` will be equal to `undefined`. We should not really worry about it, since under this condition to baseType is no longer appeals. But this implicit behavior, which in the further development can lead to errors. That it could not happen, we need to explicitly specify the behavior for this case. In the near future I'll do it.

**Comment by figliohulio** [comment]
#116.

**Comment by figliohulio** [comment]
#116

**Comment by figliohulio** [comment]
Please review my pull-request: #116.
